### ISSUE TITLE
Package not found

### ISSUE THREAD

**Issue by cyr-l** [cwaring/meteor-cssnext#1]
Hi,

When running the command `meteor add kit:cssnext` I get an error: "error: no such package".

I saw [somewhere](https://forums.meteor.com/t/how-to-install-meteor-package-direct-from-github/1693) that I should be able to install it from GitHub but I don't know what packages directory they're talking about.

**Comment by cwaring** [comment]
Hey there, you win points for being keen as I haven't actually released this yet. However it is functional so I can push out an initial version if you would like to help beta test it?

**Comment by cyr-l** [comment]
Haha - blame Google there.

Sure!

First Meteor project here - I'm a bit scared since I know I'm talking to a specialist! ^^

**Comment by cwaring** [comment]
Well be brave and dive it, I'm sure you'll have fun!

0.1.0 is now live, feel free to give it a spin and let me know how you get on: https://atmospherejs.com/kit/cssnext

**Comment by cyr-l** [comment]
Thanks!

Psst: meanwhile I figured I could create a `packages` directory in my Meteor project and clone your repo there.

**Comment by cwaring** [comment]
Yes that works too. If you want to work with local packages I would suggest setting a `PACKAGE_DIRS` environment variable to a global folder outside of your Meteor app, then you can clone dev packages into there (or build your own) and include them using the usual `meteor add package:name`.

Here's a bit more info: http://themeteorchef.com/recipes/writing-a-package/

**Comment by cyr-l** [comment]
Thank you. I'll give it a go then.

Well, the cssnext package seems to be working fine, based on the basic tests I just did ;)

**Comment by cwaring** [comment]
:+1: 

If you have any ideas or issues just jump on here and I'll help you out :)

**Comment by cyr-l** [comment]
Wow. That support tho. Kindest issue/convo ever :)

Since you insist…

My aim is now to compose a custom Basscss stylesheet (Bassplate?). I want to only keep the needed components and customize some properties like `—h0` and friends in the `:root` selector for instance.

The nirvana would be reached if I could write my stylesheets in Sass before being processed by cssnext.

**Comment by cwaring** [comment]
Ah interesting you mention basscss as that's what drove me to write this package initially. I have a similar intention and [have been working on an extension](https://github.com/cwaring/meteor-basscss/tree/new/compile-plugin) for this package to include basscss in the compile path but due to a Meteor bug it's been stalled for a while.

When the new meteor build pipeline is released I should be able to pick this back up, stay tuned! :)

**Comment by cyr-l** [comment]
Interesting but it makes sense. Your Basscss (published ;)) package led me here.

It sounds like a plan!

**Comment by cwaring** [comment]
@cbioley I've published a new package to dynamically compile basscss, please test it out when you have chance :)
https://atmospherejs.com/kit/cssnext-basscss

**Comment by cyr-l** [comment]
Hey! 

Awesome sauce! Thanks for not having me left behind :)

Just ran the `add` command in a pristine Meteor project and got an error:

```
meteor add kit:cssnext-basscss
=> Errors while adding packages:

While checking for kit:cssnext-basscss@0.1.0:
error: No compatible binary build found for this package. Contact the package
author and ask them to publish it for your platform.
```

I admit I have not tried (yet) to find the cause.

**Comment by cwaring** [comment]
ah, what OS platform are you on? The Meteor build servers were down
yesterday so it may not of compiled correctly for all environments.

I've just kicked it off again so try in about 10 min then hopefully it will
work :)

Chris

@cwaring http://twitter.com/cwaring / WWAVES http://wwaves.co/

**Comment by cyr-l** [comment]
OS X.

Fixed, yay!

Now, how would you recommend getting all the npm packages defined in basscss.next.css (basscss-base-reset, basscss-base-forms, ...)?

**Comment by cwaring** [comment]
They are all included in the package along with the optional modules. Just
@import them as you would with bassplate.

More info in the readme: https://github.com/cwaring/meteor-cssnext-basscss

Chris

@cwaring http://twitter.com/cwaring / WWAVES http://wwaves.co/

**Comment by cyr-l** [comment]
Sorry, I had read it, but I asked because of an error on the first import:

<pre>
=> Errors prevented startup:
   While building the application:
   client/lib/basscss.next.css: cssnext compiler error:
   /Users/cik/code/alumni-meteor/meteor/client/lib/basscss.next.css:12:1: Failed to
   find 'basscss-base-reset' from /Users/cik/code/alumni-meteor/meteor
   in [
   /Users/cik/code/alumni-meteor/meteor/client/lib,
   /Users/cik/code/alumni-meteor/meteor/packages/kit:cssnext-basscss/.npm/plugin/cssnext-basscss/node_modules/basscss/node_modules/,
   /Users/cik/code/alumni-meteor/meteor/packages/kit:cssnext-basscss/.npm/plugin/cssnext-basscss/node_modules/
   ]
=> Your application has errors. Waiting for file change.
</pre>

**Comment by cwaring** [comment]
Ha you're right. Sorry that's my fault. Looks like some of the paths change after building, I'll investigate later and get back to you. Sooooo close :)

**Comment by cyr-l** [comment]
You're a sweetheart ^^

No pressure, no pressure!

**Comment by cwaring** [comment]
I try :)

New version is out that hopefully fixed this issue: `meteor add kit:cssnext-basscss@0.2.0`

**Comment by cyr-l** [comment]
I'm so sad...

Now that it works (w00t! BTW), I will lose a fellow ;)

Thank you very much Chris.

**Comment by cwaring** [comment]
Ha, good news but I'm sure there will always be bugs ;)

Thanks for helping out!

Chris

@cwaring http://twitter.com/cwaring / WWAVES http://wwaves.co/
